import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.*;

public class Notes extends JPanel implements Serializable {
    private JTextArea textArea1;
    private JButton dodajButton;
    private JComboBox comboBox1;
    private JPanel panel1;
    private JLabel labelTitle;

    Map<Date, String> notes = new TreeMap<>();

    private String title = "Notes";
    private int maxNumberOfNotes = 20; //ograniczona - jak ktoś da mniej niż 10 to veto

    public Notes() {
        $$$setupUI$$$();

        textArea1.setEditable(false);
        labelTitle.setText(title);

        notes.put(new Date(90, 10, 31), "Najstarsza notatka.");
        notes.put(new Date(96, 2, 24), "Stara notatka.");
        notes.put(new Date(106, 2, 24), "Nowsza notatka.");


        updateGUI();

        dodajButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (notes.size() >= maxNumberOfNotes) {
                    JOptionPane.showMessageDialog(null, "Nie mozna wprowadzic wiecej notatek!", "ERROR", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                Date now = new Date();
                String note = JOptionPane.showInputDialog("Nowa notatka:");
                notes.put(now, note);
                updateGUI();
            }
        });
        comboBox1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date date = (Date) comboBox1.getSelectedItem();
                try {
                    textArea1.setText(notes.get(date));
                } catch (NullPointerException e1) {
                    textArea1.setText("");
                }
            }
        });
    }

    private void updateGUI() {
        comboBox1.removeAllItems();
        for (Date date : notes.keySet()) {
            comboBox1.addItem(date);
        }
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public int getMaxNumberOfNotes() {
        return maxNumberOfNotes;
    }

    public void setMaxNumberOfNotes(int maxNumberOfNotes) {
        this.maxNumberOfNotes = maxNumberOfNotes;
    }


    private void createUIComponents() {
        panel1 = this;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel1.setLayout(new GridBagLayout());
        dodajButton = new JButton();
        dodajButton.setText("Dodaj");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 5;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(dodajButton, gbc);
        comboBox1 = new JComboBox();
        comboBox1.setMinimumSize(new Dimension(300, 26));
        comboBox1.setPreferredSize(new Dimension(300, 26));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(comboBox1, gbc);
        labelTitle = new JLabel();
        labelTitle.setFont(new Font(labelTitle.getFont().getName(), labelTitle.getFont().getStyle(), 48));
        labelTitle.setMaximumSize(new Dimension(300, 64));
        labelTitle.setMinimumSize(new Dimension(300, 64));
        labelTitle.setPreferredSize(new Dimension(300, 64));
        labelTitle.setText("Notatki");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(labelTitle, gbc);
        final JScrollPane scrollPane1 = new JScrollPane();
        scrollPane1.setEnabled(true);
        scrollPane1.setMinimumSize(new Dimension(300, 19));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(scrollPane1, gbc);
        textArea1 = new JTextArea();
        textArea1.setEnabled(true);
        textArea1.setMinimumSize(new Dimension(0, 100));
        textArea1.setPreferredSize(new Dimension(0, 100));
        scrollPane1.setViewportView(textArea1);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel1.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(spacer2, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(spacer3, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel1.add(spacer4, gbc);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(spacer5, gbc);
        final JPanel spacer6 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel1.add(spacer6, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
