import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.beans.PropertyVetoException;
import java.beans.VetoableChangeListener;
import java.io.Serializable;
import java.util.*;

public class Notes extends JPanel implements Serializable {
    private static final long serialVersionUID = 1L;

    private TextField textArea1;
    private JButton dodajButton;
    private ListOfNotes comboBox1;
    private JPanel panel1;
    private JLabel labelTitle;
    private JButton usuńButton;

    private String title = "Notes"; //prosta

    public Notes() {
        $$$setupUI$$$();

        textArea1.setEditable(false);
        labelTitle.setText(title);

        updateGUI();

        dodajButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (comboBox1.getNotes().size() >= comboBox1.getMaxNumberOfNotes()) {
                    JOptionPane.showMessageDialog(null, "Nie mozna wprowadzic wiecej notatek!", "ERROR", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                Date now = new Date();
                String note = JOptionPane.showInputDialog("Nowa notatka:");
                comboBox1.getNotes().put(now, note);
                updateGUI();
            }
        });
        comboBox1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date date = (Date) comboBox1.getSelectedItem();
                try {
                    textArea1.setText(comboBox1.getNotes().get(date));
                } catch (NullPointerException e1) {
                    textArea1.setText("");
                }
            }
        });
        usuńButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date date = (Date) comboBox1.getSelectedItem();
                comboBox1.getNotes().remove(date);
                updateGUI();
            }
        });

        comboBox1.addVetoableChangeListener(new VetoableChangeListener() {
            @Override
            public void vetoableChange(PropertyChangeEvent evt) throws PropertyVetoException {
                int v = ((Integer) evt.getNewValue()).intValue();
                if (v < 10)
                    throw new PropertyVetoException("number too small",
                            evt);
            }
        });
        textArea1.addPropertyChangeListener(new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                String name = evt.getPropertyName();
                if (name.equals("customPreferredWidth")) {
                    int width = ((Integer) evt.getNewValue()).intValue();
                    textArea1.setPreferredSize(new Dimension(width, textArea1.getHeight()));
                    labelTitle.setPreferredSize(new Dimension(width, labelTitle.getHeight()));
                    comboBox1.setPreferredSize(new Dimension(width, comboBox1.getHeight()));
                }
            }
        });
    }

    private void updateGUI() {
        comboBox1.removeAllItems();
        for (Date date : comboBox1.getNotes().keySet()) {
            comboBox1.addItem(date);
        }
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    private void createUIComponents() {
        panel1 = this;
        comboBox1 = new ListOfNotes();
        textArea1 = new TextField();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel1.setLayout(new GridBagLayout());
        dodajButton = new JButton();
        dodajButton.setText("Dodaj");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 6;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.SOUTH;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(dodajButton, gbc);
        comboBox1.setMinimumSize(new Dimension(300, 26));
        comboBox1.setPreferredSize(new Dimension(300, 26));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(comboBox1, gbc);
        final JScrollPane scrollPane1 = new JScrollPane();
        scrollPane1.setEnabled(true);
        scrollPane1.setMinimumSize(new Dimension(300, 19));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.gridheight = 5;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(scrollPane1, gbc);
        textArea1.setEnabled(true);
        textArea1.setMinimumSize(new Dimension(0, 100));
        textArea1.setPreferredSize(new Dimension(0, 100));
        scrollPane1.setViewportView(textArea1);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 10;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel1.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(spacer2, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.gridheight = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(spacer3, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel1.add(spacer4, gbc);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 5;
        gbc.gridheight = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(spacer5, gbc);
        final JPanel spacer6 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel1.add(spacer6, gbc);
        usuńButton = new JButton();
        usuńButton.setText("Usuń");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 8;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(usuńButton, gbc);
        final JPanel spacer7 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 9;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel1.add(spacer7, gbc);
        final JPanel spacer8 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 7;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel1.add(spacer8, gbc);
        labelTitle = new JLabel();
        labelTitle.setFont(new Font(labelTitle.getFont().getName(), labelTitle.getFont().getStyle(), 48));
        labelTitle.setMaximumSize(new Dimension(300, 64));
        labelTitle.setMinimumSize(new Dimension(300, 64));
        labelTitle.setPreferredSize(new Dimension(300, 64));
        labelTitle.setText("Notatki");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(labelTitle, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
